# SPDX-License-Identifier: Apache-2.0
# Copyright 2023 Atlan Pte. Ltd.
name: "Merge"

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    name: "Sphinx"
    strategy:
      matrix:
        python-version: [ "3.9" ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
      - name: Build Sphinx
        id: deployment
        uses: sphinx-notes/pages@v3
        with:
          publish: false
      - name: Publish Sphinx
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ steps.deployment.outputs.artifact }}
